import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });



interface CustomMetadata {
  title: string;
  description: string;
  icons?: { rel: string; url: string }[];
}

export const metadata: CustomMetadata = {
  title: "Music School",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="relative w-full flex items-center justify-center">
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
